CREATE TABLE IF NOT EXISTS logs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pet_name VARCHAR(191) NOT NULL,
  task VARCHAR(100) NOT NULL,
  time DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_logs_time (time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

